on:
  push:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2.5.0
      - run: pwsh -File generate_name.ps1
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
  
  job3:
    needs: 
      - job1
      - job2
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
    
